# Generated by Django 4.2.8 on 2023-12-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_payroll_placeofsupply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='placeofsupply',
        ),
    ]
