# Generated by Django 4.2.8 on 2023-12-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0005_salary_deatils_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_deatils',
            name='employee_othercuttings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
